var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__9ab90f4c._.js")
R.c("server/chunks/ssr/7db23_next_dist_4bde90bb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__f47ae38e._.js")
R.c("server/chunks/ssr/7db23_next_dist_56a242bd._.js")
R.c("server/chunks/ssr/OneDrive_Desktop_New folder_visionai-career-advisor_src_app_79f9fdae._.js")
R.c("server/chunks/ssr/[root-of-the-server]__c95c14bd._.js")
R.c("server/chunks/ssr/7db23_next_dist_client_components_3a23b160._.js")
R.c("server/chunks/ssr/7db23_next_dist_client_components_builtin_forbidden_ff3e9119.js")
R.c("server/chunks/ssr/[root-of-the-server]__114aa3fe._.js")
R.c("server/chunks/ssr/OneDrive_Desktop_New folder_visionai-career-advisor_a53849e9._.js")
R.c("server/chunks/ssr/7db23_next_dist_65b02357._.js")
R.m(86982)
R.m(44126)
module.exports=R.m(44126).exports
